
_base_: '../__base__/mist_er.yaml'

runner: PyrmidP2P_Runner
model:
  model_name: PyrmidP2P
  model_G: 
    model_name: resnet_9blocks
    input_nc: 3
    output_nc: 3
    ngf: 64
    norm: instance
    no_dropout: False
    init_type: normal
    init_gan: 0.02
    optimizer: 
      optimizer: Adam
      beta1: 0.5
      lr: 2.e-4
      weight_decay: 0.000
    lr_scheduler:
      type: linear
      

  model_D:
    model_name: basic
    norm: instance
    ndf: 64
    n_layer_D: 3 
    init_type: normal
    init_gan: 0.2
    optimizer: 
      optimizer: Adam
      beta1: 0.5
      lr: 2.e-4
      weight_decay: 0.000
    lr_scheduler:
      type: linear # for 100 epoch strict the same with ori repo
      # when we do experiment on 40 epoch,we use plateau
      
training:
  n_epochs: 100
  n_epochs_decay: 100

lambda_loss_fn:
  gan_mode: vanilla
  lambda_GAN: 1.0
  lambda_L1: 25
  weight_L2: 25
  weight_L3: 25
  weight_L4: 25
  