
_base_: '../__base__/mist_er.yaml'

runner: RegGAN_Runner
model:
  # modified params
  nce_idt: True
  nce_layers: '0,4,8,12,16'
  nce_T: 0.07
  num_patches: 256
  flip_equivariance: False
  nce_includes_all_negatives_from_minibatch: False
  model_name: RegGAN
  model_G: 
    model_name: resnet_9blocks
    input_nc: 3
    output_nc: 3
    ngf: 64
    norm: instance
    no_dropout: False
    init_type: normal
    init_gan: 0.02
    optimizer: 
      optimizer: Adam
      beta1: 0.5
      lr: 2.e-4
      weight_decay: 0.000
    lr_scheduler:
      type: linear
      

  model_D:
    model_name: basic
    norm: instance
    ndf: 64
    n_layer_D: 3 
    init_type: normal
    init_gan: 0.2
    optimizer: 
      optimizer: Adam
      beta1: 0.5
      lr: 2.e-4
      weight_decay: 0.000
    lr_scheduler:
      type: linear # for 100 epoch strict the same with ori repo
      # when we do experiment on 40 epoch,we use plateau
  
  model_R:
    optimizer: 
      optimizer: Adam
      beta1: 0.5
      lr: 2.e-4
      weight_decay: 0.000
    lr_scheduler:
      type: linear # for 100 epoch strict the same with ori repo
      # when we do experiment on 40 epoch,we use plateau
  model_F:
    model_name: mlp_sample
    netF_nc: 256


lambda_loss_fn:
  gan_mode: lsgan
  lambda_GAN: 1.0
  lambda_Cyc: 10
  lambda_Corr: 20
  lambda_Smooth: 0.0001
  
  