
data:
  dataset_name: 'BCI_dataset'
  dataset_type: "IHCDataset"
  dataset_config:
    dataroot: /root/Desktop/data/private/Dataset4Research/BCI_dataset
    load_size: 1024
    crop_size: 512
    subclass: ['HE','IHC']
  train:
    batch_size: 1
    shuffle: True
  val:
    batch_size: 1
    shuffle: True

training:
  n_epochs: 40
  save_interval: 500
  save_pth_interval: 5
  accumulate_grad_batches: 2
  n_epochs_decay: 10
  resume_checkpoint: None