
_base_: '../__base__/mist_her2.yaml'

runner: PyrmidP2P_Runner
model:
  model_name: PyrmidP2P
  model_G: 
    model_name: resnet_9blocks
    input_nc: 3
    output_nc: 3
    ngf: 64
    norm: instance
    no_dropout: False
    init_type: normal
    init_gan: 0.02
    optimizer: 
      optimizer: Adam
      beta1: 0.5
      lr: 2.e-4
      weight_decay: 0.000
    lr_scheduler:
      factor: 0.5
      patience: 3000
      threshold: 0.0001
      cooldown: 3000
      min_lr: 5.e-7

  model_D:
    model_name: basic
    norm: instance
    ndf: 64
    n_layer_D: 3 
    init_type: normal
    init_gan: 0.2
    optimizer: 
      optimizer: Adam
      beta1: 0.5
      lr: 2.e-4
      weight_decay: 0.000
    lr_scheduler:
      factor: 0.5
      patience: 3000
      threshold: 0.0001
      cooldown: 3000
      min_lr: 5.e-7
  
lambda_loss_fn:
  gan_mode: vanilla
  lambda_GAN: 1.0
  lambda_L1: 25
  weight_L2: 25
  weight_L3: 25
  weight_L4: 25